baseurl = "/"
languageCode = "en-us"
title = "The Jade Shola"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "The Jade Shola"
	description = "Website Describing the Eco restoration and regeneration carried out at Jade Shola"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Welcome to Heaven on Earth!!** <br> a tiny shred of the native ecosystem <br> lovingly preserved for you <br> by passionate sons of the soil"
		# The icons will be shown if you enter your username
		twitter = "mugu"
		facebook = "mugu"
		linkedin = "mugu"

		copyright = [
			"&copy; Mugunthan Ganapathy"
		]


	[params.about]
		hide  = false
		title = "The Jade Shola"
		content = "We are a small family run outfit from a tribe who have been living in these gorgeous mountains in harmony for hundreds of years. We are passionate about saving what is left of this wonderful land from the ravages of modernisation. We are trying to do our bit by trying to regenerate native flora in what is left of our ancestral lands"


	[params.portfolio]
		hide  = false
		title = "Gallery"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Over the Top"
			description = "View of the Kalhatti slopes from Jade Shola"

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "HSssss"
			description = "Guest houses at Jade Shola for our slithery friends..."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Strobilanthes kunthiana"
			description = "The Kurinji shrub growing in Jade Shola"

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Syzygium cumini"
			description = "The Naaval tree"

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Solur"
			description = "The Solur highlands form a beautiful backdrop to Jade Shola"

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Howdy tiny people.."
			description = "The local tusker has left his calling card at Jade Shola"

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "We would love to help you experience these magical highlands and share our Joy. Interested? Contact us!!"

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "11.483989,76.699126"
		address = [
			"Pine view Stay",
			"184 BellieMaistry Lane",
			"Fingerpost Ooty",
			"The Nilgiris 643 006"
		]
		phone = "+91 99430 06000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "jadeshola.nilgiris@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
 [[menu.main]]
  name = "Home"
  url  = "/"
  weight = 0

 [[menu.main]]
  name = "About"
  url  = "about"
  weight = 5

 [[menu.main]]
  name = "Blog"
  url  = "post/"
  weight = 10
